# permissions for end users to edit mviweldings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mviwelding-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mviwelding
    app.kubernetes.io/part-of: mviwelding
    app.kubernetes.io/managed-by: kustomize
  name: mviwelding-editor-role
rules:
- apiGroups:
  - mvi.mviwelding.ai
  resources:
  - mviweldings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mvi.mviwelding.ai
  resources:
  - mviweldings/status
  verbs:
  - get
